version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  # api:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/todo_db
  #     JWT_SECRET: supersecret_jwt_key_change_me
  #     PORT: 4000
  #   ports:
  #     - "4000:4000"
volumes:
  db-data:
